# define the configfiles
configfile: 'config/test.yaml'
configfile: 'config/config.yaml'
configfile: 'config/sample.yaml'

# include the rules
include: 'rules/test.smk'
include: 'rules/spaceranger_processing.smk'

# ask for all the samples
rule spaceranger_minimal:
    '''
    rule to run the default analysis using cellranger.
    '''
    input:
        expand(rules.runSpaceranger.output.output,sample=config['SAMPLES'])

# default rule to run the cellranger pipeline
rule spaceranger_default:
    '''
    rule to run the default analysis using spaceranger.
    '''
    input:
        expand(rules.moveSpacerangerSummary.output.summary, sample=config['SAMPLES']),
        rules.runMultiqc1.output.html


rule test_all:
    input:
        rules.test.output.test